name: Build Mobirise Extension

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Create Downloadable Mobirise Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Create Mobirise Extension File
        run: zip -r yasinc2-reload-userblocks.mbrext ./* -x ".git/*" ".github/*" "README.md" "LICENSE"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload Release
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./yasinc2-reload-userblocks.mbrext
          asset_name: yasinc2-reload-userblocks.mbrext
          asset_content_type: application/zip
