name: Build Mobirise Extension

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Downloadable Mobirise Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This ensures that the full Git history is checked out, not just the latest commit

      - name: Create a release with a custom name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          RELEASE_NAME="Release for $TAG_NAME"
          gh release create $TAG_NAME --title "$RELEASE_NAME" --notes "Custom release for tag $TAG_NAME"  --generate-notes

      - name: Create Mobirise Extension File
        run: zip -r yasinc2-reload-userblocks.mbrext ./* -x ".git/*" ".github/*" "README.md" "LICENSE"
      
      - name: Upload asset to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          gh release upload $TAG_NAME yasinc2-reload-userblocks.mbrext
